CREATE DATABASE burgers_db;
USE fw2tcmcb7awewtep;

CREATE TABLE burgers
(
id INTEGER NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(45) NOT NULL,
devoured BOOLEAN DEFAULT FALSE,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);


SELECT * FROM burgers
